import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#141124",
        surface: "#141124",
        "surface-dim": "#141124",
        "surface-bright": "#3a374b",
        "surface-variant": "#353247",
        "surface-container-lowest": "#0e0c1e",
        "surface-container-low": "#1c192c",
        "surface-container": "#201d30",
        "surface-container-high": "#2a273b",
        "surface-container-highest": "#353247",
        "on-surface": "#e5dffa",
        "on-surface-variant": "#c3c6d6",
        "on-background": "#e5dffa",
        "on-primary": "#002a78",
        "on-primary-container": "#00256c",
        "on-secondary": "#351684",
        "on-secondary-container": "#beadff",
        "on-tertiary": "#342c49",
        "on-tertiary-container": "#2e2642",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        primary: "#b4c5ff",
        "primary-container": "#638cff",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#003ea8",
        secondary: "#ccbeff",
        "secondary-container": "#4e359d",
        "secondary-fixed": "#e7deff",
        "secondary-fixed-dim": "#ccbeff",
        "on-secondary-fixed": "#1f0060",
        "on-secondary-fixed-variant": "#4c339b",
        tertiary: "#cdc1e5",
        "tertiary-container": "#988caf",
        "tertiary-fixed": "#eaddff",
        "tertiary-fixed-dim": "#cdc1e5",
        "on-tertiary-fixed": "#1f1732",
        "on-tertiary-fixed-variant": "#4b4260",
        error: "#ffb4ab",
        "error-container": "#93000a",
        outline: "#8d909f",
        "outline-variant": "#434653",
        "inverse-surface": "#e5dffa",
        "inverse-on-surface": "#312e42",
        "inverse-primary": "#2656c7",
        "surface-tint": "#b4c5ff",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "Segoe UI", "Roboto", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "Consolas", "monospace"],
      },
      boxShadow: {
        card: "0 1px 3px 0 rgb(0 0 0 / 0.4)",
        modal:
          "0 24px 48px -12px rgb(0 0 0 / 0.6), 0 0 0 1px rgb(99 140 255 / 0.08), 0 4px 16px rgb(0 0 0 / 0.4)",
      },
    },
  },
  plugins: [],
};

export default config;
